CREATE TABLE quote
(
    id        BIGSERIAL    PRIMARY KEY,
    text      VARCHAR(512) NOT NULL,
    source    VARCHAR(144) NOT NULL,
    tag       VARCHAR(32)  NULL,
    link      VARCHAR(128) NULL
);


INSERT INTO quote(text,source,tag) VALUES ('They put a hot wire to my head / Because of the things I did and said', '"Rise" - Public Image Ltd.', null);
INSERT INTO quote(text,source,tag) VALUES ('Anger is an energy.', '"Rise" - Public Image Ltd.', null);
INSERT INTO quote(text,source,tag) VALUES ('Virgil Cain is my name and I served on the Danville train.', '"The Night They Drove Old Dixie Down"-The Band', null);
INSERT INTO quote(text,source,tag) VALUES ('I love it when you call me Big Poppa', '"Big Poppa" - Notorious B.I.G.', null);
INSERT INTO quote(text,source,tag) VALUES ('Can I kick it? Yes you can.', '"Can I Kick It?" - A Tribe Called Quest', null);
INSERT INTO quote(text,source,tag) VALUES ('We are not monsters, we''re moral people / And yet we have the strength to do this.', '"Nemesis"-Shreikback', null);
INSERT INTO quote(text,source,tag) VALUES ('We are like Greeks. We are like Romans. / Centaurs and monkeys just cluster ''round us', '"Nemesis"-Shreikback', null);
INSERT INTO quote(text,source,tag) VALUES ('I''m gonna tell you how it''s gonna be.', '"Not Fade Away"-The Rolling Stones', null);
INSERT INTO quote(text,source,tag) VALUES ('Beware doll, you''re bound to fall', '"Like a Rolling Stone" - Bob Dylan', null);
INSERT INTO quote(text,source,tag) VALUES ('And Harry doesn''t mind if he doesn''t make the scene.', '"Sultans of Swing" - Dire Straits', null);
INSERT INTO quote(text,source,tag) VALUES ('I just keep on rolling along with the grace of the Lord above.', '"Heartbreaker" - Led Zepplin', null);
INSERT INTO quote(text,source,tag) VALUES ('Sometimes we''re not prepared for adversity.', '"Mercy, Mercy, Mercy" - The Cannonball Adderly Quartet', null);
INSERT INTO quote(text,source,tag) VALUES ('Funky Claude was running in and out / pulling kids out the ground', '"Smoke On the Water" - Deep Purple', null);
INSERT INTO quote(text,source,tag) VALUES ('They smelled of pubs and Wormwood Scrubs and too many right wing meetings.', '"Down in the Tube Station at Midnight" - The Jam', null);
INSERT INTO quote(text,source,tag) VALUES ('This dance ain''t for everybody. Only the sexy people.', '"Push It" - Salt-n-Pepa', null);
INSERT INTO quote(text,source,tag) VALUES ('Four young chiquitas in Omaha waitin'' for the band to return from the show.', '"We''re an American Band" - Grand Funk Railroad', 'neb-omaha');
INSERT INTO quote(text,source,tag) VALUES ('The name is Big Daddy, yes big not little.', '"Ain''t No Half Steppin''" - Big Daddy Kane', null);
INSERT INTO quote(text,source,tag) VALUES ('Just tell me where it hurts and I''ll tell you who to call.', '"Quinn the Eskimo" - Bob Dylan', null);
INSERT INTO quote(text,source,tag) VALUES ('You just want to be on the side that''s winning.', '"Positively 4th Street" - Bob Dylan', null);
INSERT INTO quote(text,source,tag) VALUES ('Don''t you understand that''s not my problem?', '"Positively 4th Street" - Bob Dylan', null);
INSERT INTO quote(text,source,tag) VALUES ('All my failings exposed, gets a taste in my mouth as desperation takes hold', '"Love Will Tear Us Apart" - Joy Division', null);
INSERT INTO quote(text,source,tag) VALUES ('Tire tracks all across your back - I can see you''ve had your fun.', '"Crosstown Traffic"- Jimi Hendrix', null);
INSERT INTO quote(text,source,tag) VALUES ('Why don''t you get back into bed.', '"Reasons to be Cheerful, Part 3" - Ian Dury & the Blockheads', null);
INSERT INTO quote(text,source,tag) VALUES ('The juice of the carrot, the smile of the parrot / A little drop of claret - anything that rocks', '"Reasons to be Cheerful, Part 3" - Ian Dury & the Blockheads', null);
INSERT INTO quote(text,source,tag) VALUES ('He just grinned and shook my hand, "No" was all he said.', '"The Weight" - The Band', null);
INSERT INTO quote(text,source,tag) VALUES ('Then she opened up a book of poems and handed it to me, written by an Italian poet from the thirteenth century.', '"Tangled Up in Blue" - Bon Dylan', null);
INSERT INTO quote(text,source,tag) VALUES ('I know you''re dissatisfied with your position and your place.', '"Positively 4th Street" - Bob Dylan', null);
INSERT INTO quote(text,source,tag) VALUES ('I don''t know why I let that mean woman make me a fool.', '"Whipping Post" - The Allman Brothers', null);
INSERT INTO quote(text,source,tag) VALUES ('I had ''em all out there steppin'' and fetchin'' like their heads were on fire and their asses was catchin''.', '"The Ballad of Uneasy Rider" - Charlie Daniels', null);
INSERT INTO quote(text,source,tag) VALUES ('And I''m so pilled up that I rattle.', '"Revolution Rock" - The Clash', null);
INSERT INTO quote(text,source,tag) VALUES ('I have got the sharpest knife, so I get the biggest slice.', '"Revolution Rock" - The Clash', null);
INSERT INTO quote(text,source,tag) VALUES ('Blood in the streets in the town of New Haven', '"Peace Frog" - The Doors', 'yale');
INSERT INTO quote(text,source,tag) VALUES ('We need the funk.', '"Give Up the Funk" - Parliament', null);
INSERT INTO quote(text,source,tag) VALUES ('And the sound that I''m hearing is only the sound of the low spark of high heeled boys.', '"The Low Spark of High Heeled Boys" - Traffic', null);
INSERT INTO quote(text,source,tag) VALUES ('And the only safe place to live is on an Indian reservation.', '"Ball of Confusion" - The Temptations', null);
INSERT INTO quote(text,source,tag) VALUES ('Well you know that it''s a shame and a pity you were raised up in the city / And you never learned nothing about country ways', '"Not So Sweet Martha Lorraine" - Country Joe and the Fish', null);
INSERT INTO quote(text,source,tag) VALUES ('Ich lieb dich nicht; Du liebst mich nicht.', '"Da da da" - Trio', null);
INSERT INTO quote(text,source,tag) VALUES ('Tap turns on the water, see the waters flow.', '"Tap Turns on the Water" - C.C.S.', null);
INSERT INTO quote(text,source,tag) VALUES ('Rhonda had a house in Venice, lived on brown rice and cocaine.', '"88 Lines About 44 Women" - The Nails', null);
INSERT INTO quote(text,source,tag) VALUES ('Everybody''s in despair, every girl and boy.', '"Quinn the Eskimo" - Bob Dylan', null);
INSERT INTO quote(text,source,tag) VALUES ('Lord Lucan is missing.', '"Lord Lucan is Missing" - The Dodgems', null);
INSERT INTO quote(text,source,tag) VALUES ('Today Billie Joe McAllister jumped off the Tallahatchee Bridge', '"Ode to Billie Joe" - Bobbie Gentry', null);
INSERT INTO quote(text,source,tag) VALUES ('The tide is high, but I''m holding on.', '"The Tide is High" - Blondie', null);
INSERT INTO quote(text,source,tag) VALUES ('And with the way you look I understand you''re not impressed.', '"Alison" - Elvis Costello', null);
INSERT INTO quote(text,source,tag) VALUES ('But spirit is something that no one destroys.', '"The Low Spark of High Heeled Boys" - Traffic', null);
INSERT INTO quote(text,source,tag) VALUES ('Don''t talk to me about your big, big heroes', '"Kelly''s Heroes" - Black Grape', null);
INSERT INTO quote(text,source,tag) VALUES ('Trouble''s gonna come to you', '"Your Time is Gonna Come" - Led Zepplin', null);
INSERT INTO quote(text,source,tag) VALUES ('I don''t like drinking fancy champy, I''ll stick with Heineken beers.', '"Love Me or Hate Me" - Lady Sovereign', null);
INSERT INTO quote(text,source,tag) VALUES ('They headed down to old El Paso; thats''s where they ran into a great big hassle.', '"Take the Money and Run" - The Steve Miller Band', 'utep');
INSERT INTO quote(text,source,tag) VALUES ('I''ll write on your tombstone, "I thank you for dinner."', '"Bungle in the Jungle" - Jethro Tull', null);
INSERT INTO quote(text,source,tag) VALUES ('Taking a bite on a biscuit, the record jumps on a scratch.', '"If I Didn''t Love You" - Squeeze', null);
INSERT INTO quote(text,source,tag) VALUES ('They were all in love with Diane, they we''re doing it in Texas.', '"Pepper" - Butthole Surfers', 'texas');
INSERT INTO quote(text,source,tag) VALUES ('I got a baby''s brain and an old man''s heart', '"I''m Eighteen" - Alice Cooper', null);
INSERT INTO quote(text,source,tag) VALUES ('Let fury have the hour / Anger can be power.', '"Clampdown" - The Clash', null);
INSERT INTO quote(text,source,tag) VALUES ('I like bread and butter. I like toast and jam.', '"Bread and Butter" - The Newbeats', null);
INSERT INTO quote(text,source,tag) VALUES ('Come on down and meet your maker. Come on down and take a stand.', '"The Stand" - The Alarm', null);
INSERT INTO quote(text,source,tag) VALUES ('And of all my friends, you''ve been the best to me. / Soon will be the day when I repay you handsomely.', '"Rush" - Big Audio Dynamite', null);
INSERT INTO quote(text,source,tag) VALUES ('What''s the point of robbery when nothing is worth taking?', '"Stand and Deliver" - Adam and the Ants', null);
INSERT INTO quote(text,source,tag) VALUES ('If I had my time again / I would do it all the same.', '"Rush" - Big Audio Dynamite', null);
INSERT INTO quote(text,source,tag) VALUES ('Lights going out, and a kick in the balls.', '"That''s Entertainment" - The Jam', null);
INSERT INTO quote(text,source,tag) VALUES ('He took it all too far, but boy could he play guitar.', '"Ziggy Stardust" - David Bowie', null);
INSERT INTO quote(text,source,tag) VALUES ('He is handing the money / He is serving the food / He knows about your party / He is calling you dude.', '"Comfort Eagle" - Cake', null);
INSERT INTO quote(text,source,tag) VALUES ('With fingernails that shine like justice, and a voice that is dark like tinted glass.', '"Short Skirt Long Jacket" - Cake', null);
INSERT INTO quote(text,source,tag) VALUES ('You pay for this but they give you that.', '"Hey Hey, My My" - Neil Young', null);
INSERT INTO quote(text,source,tag) VALUES ('We live on blood / We are Sparta F.C', '"Theme from Sparta FC" - The Fall', null);
INSERT INTO quote(text,source,tag) VALUES ('You scumbag, you maggot, you cheap lousy faggot', '"Fairytale of New York" - The Pogues', null);
INSERT INTO quote(text,source,tag) VALUES ('I remember one night the kid cut off his right arm in a bid to save a bit of power.', '"So It Goes" - Nick Lowe', null);
INSERT INTO quote(text,source,tag) VALUES ('We''re only making plans for Nigel.', '"Making Plans for Nigel" - XTC', null);
INSERT INTO quote(text,source,tag) VALUES ('But anyone who ever had heart, they wouldn''t turn around and break it.', '"Sweet Jane" - Lou Reed', null);
INSERT INTO quote(text,source,tag) VALUES ('It''s tough kid, but it''s life.', '"Holiday In Cambodia" - The Dead Kennedys', null);
INSERT INTO quote(text,source,tag) VALUES ('You''ll work harder with a gun in your back, for a bowl of rice a day.', '"Holiday In Cambodia" - The Dead Kennedys', null);
INSERT INTO quote(text,source,tag) VALUES ('I''m the all night drug prowling wolf who looks so sick in sun / I''m the white man in the Palais', '"White Man in Hammersmith Palais" - The Clash', null);
INSERT INTO quote(text,source,tag) VALUES ('Space travel''s in my blood.', '"Another Girl, Another Planet" - The Only Ones', null);
INSERT INTO quote(text,source,tag) VALUES ('I''m not a coward; I''ve just never been tested.', '"The Impression That I Get" - The Mighty Mighty Bosstones', null);
INSERT INTO quote(text,source,tag) VALUES ('So let the words of our mouth and the meditation of our heart be acceptable in thy sight, O Fari!', '"By the RIvers of Babylon"-The Melodians', null);
INSERT INTO quote(text,source,tag) VALUES ('Tetrahydrocannabinol für die Allgemeinheit!', '"Mein Weed" - Nikitaman', null);
INSERT INTO quote(text,source,tag) VALUES ('I''m just like a turtle crawling out of my shell.', '"Boombastic" - Shaggy', 'maryland');
INSERT INTO quote(text,source,tag) VALUES ('I''m going to Wichita, far from this opera for evermore.', '"Seven Nation Army" - The White Stripes', 'wichita-st');
INSERT INTO quote(text,source,tag) VALUES ('In North Carolina way back in the hills, there lived my pappy and he had him a still.', '"White Lightning" - The Big Bopper', 'unc-asheville');
INSERT INTO quote(text,source,tag) VALUES ('Everybody know I''m a motherfucking monster.', '"Monster" - Kanye West', null);
INSERT INTO quote(text,source,tag) VALUES ('What ever happened to Leon Trotsky?', '"No More Heroes" - The Stranglers', null);
INSERT INTO quote(text,source,tag) VALUES ('We''re volunteers of America.', '"Volunteers" - Jefferson Airplane', 'tennessee');
INSERT INTO quote(text,source,tag) VALUES ('Now she''s with one of my good-time buddies, they''re drinking in some crosstown bar.', '"Whipping Post" - The Allman Brothers', null);
INSERT INTO quote(text,source,tag) VALUES ('Cause now I wanna be your dog.', '"I Wanna Be Your Dog" - Iggy and the Stooges', null);
INSERT INTO quote(text,source,tag) VALUES ('Well New York City really has it all.', '"Sheena Is a Punk Rocker" - The Ramones', 'columbia');
INSERT INTO quote(text,source,tag) VALUES ('That man could give a fuck about the grin on your face as you walk by randy as a goat.', '"Never Say Never" - Romeo Void', null);
INSERT INTO quote(text,source,tag) VALUES ('Free Nelson Mandela!', '"Nelson Mandela" - The Specials', null);
INSERT INTO quote(text,source,tag) VALUES ('Bitch, I''m me!', '"Stand Up" - Ludacris', null);
INSERT INTO quote(text,source,tag) VALUES ('But where the fuck is the waitress at with my drinks!', '"Stand Up" - Ludacris', null);
INSERT INTO quote(text,source,tag) VALUES ('You have to let that raga drop.', '"Rock the Casbah" - The Clash', null);
INSERT INTO quote(text,source,tag) VALUES ('All your compliments and your cutting remarks are captured here in my quotation marks.', '"Everyday I Write the Book" - Elvis Costello', null);
INSERT INTO quote(text,source,tag) VALUES ('Really don''t mind if you sit this one out.', '"Thick as a Brick" - Jethro Tull', null);
INSERT INTO quote(text,source,tag) VALUES ('Twenty-one years in captivity / His shoes too small to fit his feet', '"Nelson Mandela" - The Specials', null);
INSERT INTO quote(text,source,tag) VALUES ('Somehow I stayed thin, while the other guys got fat', '"Rush" - Big Audio Dynamite', null);
INSERT INTO quote(text,source,tag) VALUES ('Hop in my Chrysler, it''s as big as a whale and it''s about to set sail.', '"Love Shack" - The B-52''s', null);
INSERT INTO quote(text,source,tag) VALUES ('What have I done?', '"Police On My Back" - The Clash', null);
INSERT INTO quote(text,source,tag) VALUES ('Look out honey, ''cause I''m using technology', '"Search and Destroy" - Iggy and the Stooges', null);
INSERT INTO quote(text,source,tag) VALUES ('And then my good friend Shaggy says "Come spend some time, family"', '"44/876" -- Shaggy & Sting', null);
INSERT INTO quote(text,source,tag) VALUES ('Why you gotta fight wit me at Cheesecake? You know I love to go there.', '"Childs Play" - Drake', null);
INSERT INTO quote(text,source,tag) VALUES ('I''m a boss, you a worker, bitch.', '"Bodak Yellow" - Cardi B', null);
INSERT INTO quote(text,source,tag) VALUES ('This will be our year, took a long time to come', '"This Will Be Our Year" - The Zombies', null);
INSERT INTO quote(text,source,tag) VALUES ('I''m so tired of being lonely, I still have some love to give.', '"Handle With Care" - The Travelling WIlburys', null);
INSERT INTO quote(text,source,tag) VALUES ('You know he knows just exactly what the facts is.', '"Take the Money and Run" - The Steve Miller Band', null);
INSERT INTO quote(text,source,tag) VALUES ('That''s where you''ll find me, along with the lovers muggers and thieves - but they''re cool people.', '"Dirty Water" - The Standells', null);
INSERT INTO quote(text,source,tag) VALUES ('And I''m telling you son, well, it ain''t no fun staring straight down a forty-four.', '"Gimme Three Steps" - Lynyrd Skynyrd', null);
INSERT INTO quote(text,source,tag) VALUES ('Yeah, we''re just young, dumb and broke but we still got love to give.', '"Young, Dumb And Broke" - Khalid', null);
INSERT INTO quote(text,source,tag) VALUES ('Spread love- it''s the Brooklyn way.', '"Juicy" - Notorious B.I.G.', 'liu-brooklyn');
INSERT INTO quote(text,source,tag) VALUES ('Gaga googa ga ga googa ga ga goo ga ga', '"Night of the Thumpasaurus People" - Parliament', null);
INSERT INTO quote(text,source,tag) VALUES ('I want the bomb, I want the P-Funk, I want my funk uncut.', '"P-Funk (Wants to Get Funked Up)" - Parliament', null);
INSERT INTO quote(text,source,tag) VALUES ('Hallelujah, here she comes.', '"Skateaway" - Dire Straits', null);
INSERT INTO quote(text,source,tag) VALUES ('I''ve never done bad things.', '"Ashes to Ashes" - David Bowie', null);
INSERT INTO quote(text,source,tag) VALUES ('The black queen chants the funeral march, the cracked brass bells will ring / To summon back the fire witch to the court of the crimson king', '"The Court of the Crimson King" - King Crimson', 'harvard');
INSERT INTO quote(text,source,tag) VALUES ('Oh workers can you stand it, oh tell me how you can? Will you be a lousy scab or will you be a man?', '"Which Side AreYou On?" - Pete Seeger', 'eastern-ky');
INSERT INTO quote(text,source,tag) VALUES ('Hmm, you''re so pretty, not to talk to you would be a crime.', '"Baby, Baby" - The Vibrators', null);
